apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-2
  labels:
    app: my-second-app   # This is just the labels for RD
spec:
  replicas: 4
  selector:             # RS selector selects the pod based on the matchEcpression with labels on the pod.
    matchExpressions:
      - key: app
        operator: In
        values:
          - my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
        env: dev
    spec:
      containers:
      - name: nginx-test
        image: nginx:latest
