apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-2
  labels:
    app: my-second-app
spec:
  replicas: 4
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
        env: dev
    spec:
      containers:
      - name: nginx-test
        image: nginx:latest
